/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

export default function DTGBS({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/ONQKVYmtdGzyIW-I/scene.splinecode')
  return (
    <>
      <color attach="background" args={['#747682']} />
      <group {...props} dispose={null}>
        <mesh
          name="criar-documento"
          geometry={nodes['criar-documento'].geometry}
          material={materials['criar-documento Material']}
          castShadow
          receiveShadow
          position={[140.17, -86.92, 75.81]}
          rotation={[-Math.PI / 6, 0.7, Math.PI / 6]}
          scale={[0.8, 0.84, 0.61]}
        >
          <mesh
            name="Rectangle"
            geometry={nodes.Rectangle.geometry}
            material={materials['Rectangle Material']}
            castShadow
            receiveShadow
            position={[-525.15, 122.69, 147.3]}
          />
          <mesh
            name="Rectangle 2"
            geometry={nodes['Rectangle 2'].geometry}
            material={materials['Rectangle 2 Material']}
            castShadow
            receiveShadow
            position={[-525, -1, 149.55]}
          />
          <mesh
            name="Rectangle 3"
            geometry={nodes['Rectangle 3'].geometry}
            material={materials['Rectangle 3 Material']}
            castShadow
            receiveShadow
            position={[99.5, -168, 70]}
          />
        </mesh>
        <OrthographicCamera
          name="1"
          makeDefault={true}
          zoom={0.5}
          far={100000}
          near={-100000}
          position={[277.91, -102.18, 236.11]}
          rotation={[-0.05, 0.75, 0.03]}
        />
        <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
      </group>
    </>
  )
}
