/*
  Auto-generated by Spline
*/

import { useState, useRef, useEffect } from 'react';
import { useFrame } from '@react-three/fiber';
import useSpline from '@splinetool/r3f-spline';
import { OrthographicCamera } from '@react-three/drei';

export default function Facilitador({ ...props }) {
  const isSmallScreen = window.innerWidth < 768;
  const { nodes, materials } = useSpline('https://prod.spline.design/sSiJqAAFx7QBdjIm/scene.splinecode')
  const [rotationSpeed, setRotationSpeed] = useState(0.01); // adjust speed here
  const groupRef = useRef();
  
  useEffect(() => {
    groupRef.current.rotation.y = 0; // or any other initial rotation value you want

    const update = () => {
      groupRef.current.rotation.y += rotationSpeed;
    };

    const id = requestAnimationFrame(function animate() {
      update();
      requestAnimationFrame(animate);
    });

    return () => cancelAnimationFrame(id);
  }, [rotationSpeed]);

  useEffect(() => {
    // Move the group a little in the y-axis after being loaded
    groupRef.current.position.y += 0.1;
  }, []);
  
  return (
    <>
      <color attach="background" args={['#747682']} />
      <group {...props} dispose={null} ref={groupRef}>
        <mesh
          name="criar-documento"
          geometry={nodes['criar-documento'].geometry}
          material={materials['criar-documento Material']}
          castShadow
          receiveShadow
          position={[-25.99, 31.94, 90.99]}
          rotation={[-0.23, -0.17, 0.01]}
          scale={[0.82, 0.85, 0.62]}
        >
          <mesh
            name="Rectangle"
            geometry={nodes.Rectangle.geometry}
            material={materials['Rectangle Material']}
            castShadow
            receiveShadow
            position={[-119.04, 153.57, 84.45]}
            rotation={[-0.07, -0.01, 0]}
            scale={[1.23, 1.18, 1.61]}
          />
        </mesh>
        <OrthographicCamera zoom={isSmallScreen?0.35:0.6} name="1" makeDefault={true} far={100000} near={-100000} position={[0, 0, 1000]} />
        <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
      </group>
    </>
  )
}



