/*
  Auto-generated by Spline
*/
import { useState, useRef, useEffect } from 'react';
import { useFrame } from '@react-three/fiber';
import useSpline from '@splinetool/r3f-spline'
import { OrthographicCamera } from '@react-three/drei'

export default function Ravit({ ...props }) {
  const isSmallScreen = window.innerWidth < 768;
  const { nodes, materials } = useSpline('https://prod.spline.design/KHEZrR2B0VfEtlbw/scene.splinecode')
  const [rotationSpeed, setRotationSpeed] = useState(0.01); // adjust speed here
  const groupRef = useRef();

  
  useEffect(() => {
    groupRef.current.rotation.y = 0; // or any other initial rotation value you want

    const update = () => {
      groupRef.current.rotation.y += rotationSpeed;
    };

    const id = requestAnimationFrame(function animate() {
      update();
      requestAnimationFrame(animate);
    });

    return () => cancelAnimationFrame(id);
  }, [rotationSpeed]);

  useEffect(() => {
    // Move the group a little in the y-axis after being loaded
    groupRef.current.position.y += 0.1;
  }, []);

  return (
    <>
      <color attach="background" args={['#747682']} />
      <group {...props} dispose={null} ref={groupRef}>
        <group name="Group" position={[-375.23, -152.57, 31.57]} rotation={[0, -0.49, 0]}>
          <mesh
            name="noticias"
            geometry={nodes.noticias.geometry}
            material={materials['noticias Material']}
            castShadow
            receiveShadow
            position={[52.82, 343.16, -191.38]}
            rotation={[-0.32, 0.57, 0.23]}
            scale={[0.8, 0.84, 0.61]}
          />
          <mesh
            name="metas"
            geometry={nodes.metas.geometry}
            material={materials['metas Material']}
            castShadow
            receiveShadow
            position={[15.73, 44.68, 162.49]}
            rotation={[-0.1, 0.82, 0.23]}
            scale={[0.8, 0.84, 0.61]}
          />
          <mesh
            name="perfil"
            geometry={nodes.perfil.geometry}
            material={materials['perfil Material']}
            castShadow
            receiveShadow
            position={[626.76, 282.25, -440.19]}
            rotation={[-0.4, 0.4, 0.38]}
            scale={[0.8, 0.84, 0.61]}
          />
          <mesh
            name="feed"
            geometry={nodes.feed.geometry}
            material={materials['feed Material']}
            castShadow
            receiveShadow
            position={[443.46, 19.92, -202.78]}
            rotation={[-Math.PI / 6, 0.7, Math.PI / 6]}
            scale={[0.8, 0.84, 0.61]}
          />
        </group>
        <OrthographicCamera
          name="1"
          makeDefault={true}
          zoom={isSmallScreen?0.35:0.55}
          far={100000}
          near={-100000}
          position={[33.66, 121.99, 992.07]}
          rotation={[-0.12, 0.03, 0]}
        />
        <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
      </group>
    </>
  )
}



